dist: focal

addons:
  apt:
    update: true
    packages:
      - swig4.0

jobs:
  include:
    - stage: tests
      language: python
      python: "3.9"
      install:
        - pip install -e .[dev]  # Triggers cmake under the hood
      script:
        - flake8 .
        - pytest tests
    - stage: "Markdown link checks"
      language: node_js
      node_js: 17
      install:
        - npm install
      script:
        - npm run validate-links
