dist: focal

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
addons:
  postgresql: "12"
  apt:
    update: true
    packages:
      # - build-essential
      - swig4.0
      - postgresql-12-postgis-3

jobs:
  include:
    - stage: tests
      language: python
      python: "3.9"
      install:
        - pip install -e .[dev]  # Triggers cmake under the hood
      script:
      - |
        flake8 .
        pytest tests
    - stage: "Markdown link checks"
      language: node_js
      node_js: 14
      script:
        - npm install --global remark-cli remark-validate-links
        - remark -u validate-links .
        - |
          export FAILURE_THRESHOLD=0
          export warnings=`remark -u validate-links . 2>&1 | grep warning | grep "Link to unknown" | wc -l`
          if [ $warnings -gt $FAILURE_THRESHOLD ]; then
            exit 1;
          fi
